//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_prices
    {
        public int id { get; set; }
        public int good_id { get; set; }
        public double price { get; set; }
    }
}
