//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int id { get; set; }
        public string name { get; set; }

        public ICollection<Provide_offers_goods> provide_Offers_Goods { get; set; }
    }
}
