//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers_goods
    {
        public int id { get; set; }
        public int goods_id { get; set; }
        public int offer_id { get; set; }
        public int count { get; set; }
        public float price { get; set; }
        public Nullable<float> nmck { get; set; }
    }
}
